### ISSUE TITLE
Opening a new window by clicking on a line

### ISSUE THREAD

**Issue by KatharosMelancho** [AsynctaskCoffee/AsynctaskCoffee#1]
Hello! Tell me please! How can I click on a plotted line so that I can open a separate window and not an info window?

`KmlDocument Rivers; Rivers = new KmlDocument(); Rivers.parseKMLStream(getResources().openRawResource(R.raw.rivers), null); FolderOverlay kmlOverlay_rivers = (FolderOverlay)Rivers.mKmlRoot.buildOverlay(mapView, null, null,Rivers); mapView.getOverlays().add(kmlOverlay_rivers);`

**Comment by KatharosMelancho** [comment]
I just can't find the solution I need. Everything is fine with markers, but I don't understand with polygons and lines.

**Comment by AsynctaskCoffee** [comment]
Hello dude,

Have you read this ?
https://osmdroid.github.io/osmdroid/javadocs/osmdroid-android/debug/index.html?org/osmdroid/views/overlay/Polyline.OnClickListener.html

You may have to update osm version for this, add lib into project as a module and update osm version.

**Comment by AsynctaskCoffee** [comment]
Other weird solution could be getting coordinate while on map click, then check it with simple loop if it is on polyline coordinates 🦊

**Comment by KatharosMelancho** [comment]
I am using your build for offlinemap. Everything works and suits, except for this problem with clicks on kml layers.

Or the option of where to look to make the "more" button in the info window, which comes out when you click on overlays. It works initially.
